### ISSUE TITLE
Security Algorithm of networks is by default set to WEP

### ISSUE THREAD

**Issue by wow0000** [AppleIntelWifi/adapter#22]
Hello,
Every networks found is recognized by the kernel extension as WEP secured networks.
Exemple of a WPA2-PSK (AES) network 
![Img](https://i.imgur.com/q8212lI.png)
Good luck about doing this driver 👍 

Hardware:
Intel AC-8260
Xiaomi Mi Air 13.3

Logs:
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4399104/log.txt)

Note about issue #19 5G networks is now visible and network detection is really fast.

**Comment by mehmetyukcell** [comment]
Have you internet connect with intel wifi kext

**Comment by wow0000** [comment]
This kext is in developpement stage and Internet Connectivity isn't possible at this moment. Only base and networks scanning is working at this date.

**Comment by mehmetyukcell** [comment]
Thanks...

**Comment by rv32ima** [comment]
I actually don't know about this. I'm thinking that Apple80211 only parses the WPA IE when the asr_age field is non-zero, but this means implementing a scan cache... >_<

**Comment by mehmetyukcell** [comment]
https://wireless.wiki.kernel.org/_media/en/users/drivers/iwlwifi-9000-pu-b0-jf-b0-34.618819.0.tgz

**Comment by mehmetyukcell** [comment]
Dear hatf, I request a kext for intel9560 and sizleri gözlüyorum.

**Comment by rv32ima** [comment]
Duplicate issue: #26
