### ISSUE TITLE
i would like to help 

### ISSUE THREAD

**Issue by arag0re** [AppleIntelWifi/adapter#23]
hey,

i love the idea of the project and i see the benefit of it if we can get it to work.
Are you still interested in working on the project, if so you can contact me on discord or send me a mail.
Discord : arag0re#7003
Mail: antonstadie1999@gmail.com

best regards
Anton

**Comment by rv32ima** [comment]
You can typically find me in the /r/HackintoshParadise discord server [here](https://discord.gg/u8V7N5C) in the #coding channel. There is a lot to be done, and I would appreciate you taking on any of the minor hoops that are tagged "good first issue" or the like.
