### ISSUE TITLE
Bluetooth coex problem

### ISSUE THREAD

**Issue by rv32ima** [AppleIntelWifi/adapter#29]
Whenever we are doing uMAC scanning, it seems to disrupt bluetooth connectivity.
Some general questions:
* Is this because we don't setup BT_COEX as soon as possible?
* Is this an issue with HOW we set up BT_COEX?
* Is this an issue in other drivers?

**Comment by averycblack** [comment]
Should be fixed PR #37 - most likely needs more work done when associating, but it doesn't kill itself during scanning anymore.
