### ISSUE TITLE
building problem 

### ISSUE THREAD

**Issue by MohammadtaghiFarkhondekar** [AppleIntelWifi/adapter#39]
![Screen Shot 1399-01-17 at 20 43 02](https://user-images.githubusercontent.com/35239600/78503845-71f9c380-777e-11ea-93b8-85001a15eb3e.png)
![Screen Shot 1399-01-17 at 20 43 17](https://user-images.githubusercontent.com/35239600/78503847-73c38700-777e-11ea-87f2-f2051e86f18d.png)
![Screen Shot 1399-01-17 at 20 41 56](https://user-images.githubusercontent.com/35239600/78503850-758d4a80-777e-11ea-84f7-802b9032c50a.png)
![Screen Shot 1399-01-17 at 20 41 47](https://user-images.githubusercontent.com/35239600/78503853-77570e00-777e-11ea-8b22-cf50d8468bb5.png)
![Screen Shot 1399-01-17 at 20 41 35](https://user-images.githubusercontent.com/35239600/78503854-7920d180-777e-11ea-8ac6-99c8da74303d.png)
![Screen Shot 1399-01-17 at 20 42 52](https://user-images.githubusercontent.com/35239600/78503855-7aea9500-777e-11ea-9e28-fc988a025eb6.png)
![Screen Shot 1399-01-17 at 20 42 40](https://user-images.githubusercontent.com/35239600/78503858-7cb45880-777e-11ea-9b12-5fbd8450ae28.png)
![Screen Shot 1399-01-17 at 20 42 33](https://user-images.githubusercontent.com/35239600/78503860-7de58580-777e-11ea-8e6c-a4d3feea2ce7.png)
![Screen Shot 1399-01-17 at 20 42 24](https://user-images.githubusercontent.com/35239600/78503861-7f16b280-777e-11ea-8fed-3c702f998824.png)
![Screen Shot 1399-01-17 at 20 42 16](https://user-images.githubusercontent.com/35239600/78503862-80e07600-777e-11ea-8dfb-cfa264156a55.png)
![Screen Shot 1399-01-17 at 20 42 08](https://user-images.githubusercontent.com/35239600/78503864-8211a300-777e-11ea-8614-69868d3c6b16.png)
![Screen Shot 1399-01-17 at 20 43 17](https://user-images.githubusercontent.com/35239600/78503897-c8ff9880-777e-11ea-9607-bdaffe6c8c8e.png)

[AppleIntelWifiAdapterV2.kext.zip](https://github.com/AppleIntelWifi/adapter/files/4434281/AppleIntelWifiAdapterV2.kext.zip)

**Comment by MohammadtaghiFarkhondekar** [comment]
It doesn't building in my pc and output kexts is 2kb.

**Comment by lgariv** [comment]
don't know why it happens, but here's the latest verision compiled
[AppleIntelWifiAdapterV2.kext.zip](https://github.com/AppleIntelWifi/adapter/files/4434499/AppleIntelWifiAdapterV2.kext.zip)

**Comment by MohammadtaghiFarkhondekar** [comment]
I test it on AC7265 - wifi can't scan and find any wifi !!
![Screen Shot 1399-01-17 at 23 09 22](https://user-images.githubusercontent.com/35239600/78506951-8051da80-7792-11ea-9bde-aa7584a4fe0c.png)
![Screen Shot 1399-01-17 at 23 09 00](https://user-images.githubusercontent.com/35239600/78506999-cad35700-7792-11ea-93ac-7dbec2a78759.png)

![Screen Shot 1399-01-17 at 23 12 28](https://user-images.githubusercontent.com/35239600/78507015-ef2f3380-7792-11ea-8ac2-91f8c053accf.png)

**Comment by MohammadtaghiFarkhondekar** [comment]
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4434543/log.txt)

by:
log show --last boot --predicate 'process == "kernel"' | grep -i intel > ~/Desktop/log.txt

**Comment by vladdenisov** [comment]
@MohammadtaghiFarkhondekar there is a special script in `scripts` folder called `logs.sh`. It will create `log.txt` in `scripts` folder.

**Comment by MohammadtaghiFarkhondekar** [comment]
> @MohammadtaghiFarkhondekar there is a special script in `scripts` folder called `logs.sh`. It will create `log.txt` in `scripts` folder.


[log.txt](https://github.com/AppleIntelWifi/adapter/files/4434600/log.txt)

**Comment by rv32ima** [comment]
Please place your log file in device-logs.
