### ISSUE TITLE
intel wifi 9560ac dualband log.txt

### ISSUE THREAD

**Issue by mehmetyukcell** [AppleIntelWifi/adapter#42]
kext build and load with Hackintool. But not connected wifi to networks...
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4434904/log.txt)

**Comment by rv32ima** [comment]
Please read the pinned issue.

**Comment by mehmetyukcell** [comment]
I do not understand.

**Comment by rv32ima** [comment]
Do **NOT** post issues related to device support in this repo. That is what [device-logs](https://github.com/AppleIntelWifi/device-logs) is for.
