### ISSUE TITLE
Intel(R) Dual Band Wireless AC 3160

### ISSUE THREAD

**Issue by yudhnaa** [AppleIntelWifi/adapter#45]
I can turn on/off wifi but I can't scan wifi and connect.
My log: [log.txt](https://github.com/AppleIntelWifi/adapter/files/4437364/log.txt)

**Comment by mehmetyukcell** [comment]
> I can turn on/off wifi but I can't scan wifi and connect.
> 
> My log: [log.txt](https://github.com/AppleIntelWifi/adapter/files/4437364/log.txt)
> 
> 

I have the same problem. İntel 9560ac 8086:0034

**Comment by MohammadtaghiFarkhondekar** [comment]
Make issues in https://github.com/AppleIntelWifi/device-logs 
I have some issues with AC7265 ...

**Comment by yudhnaa** [comment]
> Make issues in https://github.com/AppleIntelWifi/device-logs
> I have some issues with AC7265 ...

Ok
thank you
