### ISSUE TITLE
how to get file.kext?

### ISSUE THREAD

**Issue by tran-steve** [AppleIntelWifi/adapter#5]
i dont see a kext file in my download folder

**Comment by rv32ima** [comment]
Follow the README instructions.

**Comment by tran-steve** [comment]
I still don't know the build instruction, can you explain step by step to me? thanks

**Comment by rv32ima** [comment]
Again, the build instructions and HOW to load the kext is right in the README file. I cannot provide any other instructions as it is physically impossible to be any more verbose about how to build this.
