### ISSUE TITLE
Kext can't load

### ISSUE THREAD

**Issue by Stevemoretz** [AppleIntelWifi/adapter#53]
**Describe the bug**
https://intelwifi.0xcc.pw/
Downloaded relalease kext from here and tried to load it via kextload but the error says it can't load it.
So are you aware of this sir? Becuase 6 days ago you have said you're fixing something is it related and this will be fixed too?

By the way how do I build the kext myself?I don't know I have xcode installed but I don't know how.

Thank you so much for your priceless efforts.

**Comment by dhinakg** [comment]
Known issue, #49 
There's a build script in the scripts folder. I suggest that if you don't know your way around Xcode that you stick to the builds on the website.

**Comment by Stevemoretz** [comment]
Thanks that's what I rather do too.Is the speed problem fixed in version 2?also can we now connect without filling plist?

**Comment by averycblack** [comment]
Your talking about a seperate kext (whcih we do not support here). This kext is aimed to be a more well rounded one which actually shows up as a wifi device in the menu. Right now all this does is scan for networks and show them in the menu.

**Comment by Stevemoretz** [comment]
@1Revenger1 oh my God somebody told me this the v2 of that kext in a forum.So would you please give me a link of that github page or any link possible thank you

**Comment by averycblack** [comment]
Might be thinking of zxy's kext https://github.com/zxystd/itlwm
The one from PCBeta has completely dissapeared

**Comment by Stevemoretz** [comment]
Yeah that's it it's slow and connect via a plist.Thanks man. No practical out there I guess yet.I found one though that works perfectly even perfect speed.but only connect via plist and if you turn off your Hotspot and want to connect once again that doesn't happen.I can share a link of where I found this kext:
https://www.tonymacx86.com/goto/post?id=2104418

**Comment by tvhung83** [comment]
@Stevemoretz wow, I can't believe there is one day my 9560 would work flawlessly, thank you for sharing!

**Comment by Stevemoretz** [comment]
You're welcome man,so if we ask the guy who put it there he could share the Chinese forum he's talking about, the whole thing could be open source so it could get done easier it now only needs to connect without plist and 2.4 ghz channel is done. 5ghz is slower but yet works.

**Comment by CoronaHack** [comment]
The kext was from a Chinese Forum called PCBeta, the original thread was deleted and the author was banned because of his violation of GPL v2 and not respecting PCBeta's moderators, you can get more information here:
http://bbs.pcbeta.com/viewthread-1853027-1-1.html
http://bbs.pcbeta.com/viewthread-1852880-1-1.html

**Comment by Stevemoretz** [comment]
@CoronaHack you are talking about the kext that was attached in the first note in the topic.A guy like 8 pages later mentioned a kext that works brilliant its not the same kext as the first page that author attached it's fast and stable so you gave the link about the first page one.here's the kext that I was talking about  https://www.tonymacx86.com/goto/post?id=2104418

**Comment by williambj1** [comment]
I don't think you're correct, @Stevemoretz. The one from PCBeta has the same `NSHumanReadableCopyright` as the one attached in Tonymac from your link.

**Comment by Stevemoretz** [comment]
Maybe they're on the same codebase.I'm not sure about that.
@williambj1 
Would you mind building the latest kext from P Beta forum?it was written that this is the github page:
https://github.com/zxystd/itlwm

I don't know how to build it would you mind trying?Then we'll know if they're the same.If it's as fast and as stable.

Because the first kext in the first page of Tonymac was too slow and unstable if you try that you'll definitely see the difference.Or if they're the same.If they are the same with the latter kext from the 8 page which was fast and stable.It sure means we found the source code of that stable and fast kext and we're good to go.

**Comment by williambj1** [comment]
Unfortunately, zxystd told me not to do so, I'm extremely sorry about that.

It's clear that those two kexts (itlwm and the one from Tonymac) are from different authors, I have sources provided above, and I understand Chinese, trust me.

It's just a difference of versions, I don't see any attachments related to itlwm in that thread, it's all about that banned author's work. Anyway, the discussion is already off-topic, I won't speak further and I think it's better for us to delete our posts.

**Comment by Stevemoretz** [comment]
Yeah I agree it's totally off topic.
