### ISSUE TITLE
Wifi does not appear

### ISSUE THREAD

**Issue by dpatrongomez** [AppleIntelWifi/adapter#63]
**Describe the bug**
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4535045/log.txt)

I just ran the build and load commands and no problem. But the wifi device does not appear and in log it shows me this

**Wireless card name**
`Intel Dual-Band Wireless-AC 8265`

**Comment by georgkreimer** [comment]
Same for 8260

**Comment by rv32ima** [comment]
Your logs show nothing. Please resubmit using the logging script within the scripts folder.

**Comment by WuWaA** [comment]
Same for 7260

[log.txt](https://github.com/AppleIntelWifi/adapter/files/4602667/log.txt)

**Comment by Kokkolabs** [comment]
Wifi appear now, but no connect.
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4610826/log.txt)

**Comment by duonglt305** [comment]
I have same problem with ``Intel Dual-Band Wireless-AC 7265``, this is my log
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4640455/log.txt)

**Comment by win1010525** [comment]
same for 9462. This is my log
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4648061/log.txt)

**Comment by CelestialSayuki** [comment]
My 7260 is OK

**Comment by CelestialSayuki** [comment]
Same for 9462. This is my log
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4648109/log.txt)

**Comment by Vitoli-o** [comment]
I have AC-9460 (pci8086,2526) and whilst scanning seems to be happening, no SSIDs show up.
See log: [log.txt](https://github.com/AppleIntelWifi/adapter/files/4658505/log.txt). Thanks!

Edit: Fantastic work nonetheless! :)
Edit 2: IoReg IOName

**Comment by Vitoli-o** [comment]
Anyone?

**Comment by Vitoli-o** [comment]
Was this resolved at all? I had no updates. Thanks in advance!
