### ISSUE TITLE
Missing Info.plist error

### ISSUE THREAD

**Issue by averycblack** [AppleIntelWifi/adapter#7]
The kext builds succesfully in both the scripts and in XCode, but I cannot get the kext to load anymore. Whenever the script (or I manually) run `sudo kextload AppleIntelWifiAdapterV2.kext`, I get an error in the log stating that it could not find the Info.plist. Looking in the kext though, there is an Info.plist in the correct place.

Other kexts that I build are able to be loaded and ran, so this confuses me, and was wondering if you've come across this too.

**Comment by averycblack** [comment]
Moving the build location back to ~/Library/Developer/Xcode/DerivedData/... fixed this.

**Comment by rv32ima** [comment]
Strange, the build location shouldn't be anything different? What was it set to before?

**Comment by averycblack** [comment]
`build`, according to XCode. It was seemingly putting the kext into adapter (project folder)/build/Build/Products/...
Edit: It was the Build _Products_ path I was looking at, sorry. That was 'build'

**Comment by averycblack** [comment]
This was an issue with SIP not being completely disabled. I don't know what changed with my setup to cause this, but this is an issue with my setup rather than with the kext, so I'll close this.
