### ISSUE TITLE
OpenCore Support

### ISSUE THREAD

**Issue by voltangle** [AppleIntelWifi/adapter#74]
You may heard of OpenCore. But, as I read about this kext, there is no support for OpenCore. Can you add support for OpenCore?
**Additional context**
I just wanted to migrate to OpenCore, because of support for Big Sur Beta. And I was thinking: Will I lose support for Intel Wifi cards? .

**Comment by dhinakg** [comment]
> This kext does not function yet. Do NOT install this into Clover, or /S/L/E. You WILL ruin your system.

You shouldn't be putting it in *any* bootloader for injection. Load it manually.

**Comment by voltangle** [comment]
Thanks for the help!
