### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by alexbarnsley** [AppleIntelWifi/adapter#8]
Hi there,

Nice work on the progress you've made! I installed this with a 9260 device and it gets detected as a wireless device. It can't find or connect to any networks yet though but it's the best kext I've installed so far.

I was wondering if you had a todo list of things that need doing. I've never worked in this area but I'm willing to try as I have a vested interest in getting it working

Feel free to close this when you've read it. Thanks!

**Comment by rv32ima** [comment]
Thanks! I'm making slow and steady progress on this kext. I'll make a to-do list, though, as there's a ton of things that require improvement here.
