### ISSUE TITLE
How to add Intel WiFi Support

### ISSUE THREAD

**Issue by TrickShotMLG02** [AppleIntelWifi/adapter#81]
When I download the latest release of the kext and copy it to the clover/kexts/other directory nothing happens after a reboot.
Networking Settings only Shows Bluetooth and Ethernet as before

My Wifi-Card: Intel® Dual Band-Wireless-AC 8265

**Comment by moda20** [comment]
The developers advise against the inclusion of this kext in the clover folder or S/L/E or L/E. 
you should install it manually each time you get to macOs  (each reboot/shutdown & power on).
to do so, you can load it using the kextload command :

```
sudo chmod -R 755 AppleIntelWiFFLi.kext

sudo chown -R root:wheel AppleIntelWiFFLi.kext

sudo kextload AppleIntelWiFFLi.kext
```

The two first lines are for repairing permissions and the third does the loading.
be sure to check the kext name and place the correct path to it on your system.

**Comment by TrickShotMLG02** [comment]
I did everything and the Kext isnt loading. When I try to load it with the console, it doesn‘t work

**Comment by alz3abi** [comment]
> I did everything and the Kext isnt loading. When I try to load it with the console, it doesn‘t work

Do this.

1- install Kexts to your clover kexts folder. 
2- Install HeliPort App to manage your Wifi connection

**Comment by moda20** [comment]
Make sure you don't have any other kexts that might interfere, if you have a list of kexts that you installed in L/E or clover, paste it here.
Also, what do you mean exactly by it doesn't work? does it add the wifi network in your network's control panel? or it doesn't find any networks. because as far as I know, you need to manually put the SSID and the password of the wifi network you want to connect to inside the info.plist of the kext before loading it.

**Comment by mehmetyukcell** [comment]
https://github.com/OpenIntelWireless

**Comment by moda20** [comment]
@mehmetyukcell  I download heliport, installed it but it still doesn't work with my kext. I am using the kext from this repo.
i don't know why

**Comment by TrickShotMLG02** [comment]
Thank you all guys for your replies

**Comment by TrickShotMLG02** [comment]
I have fixed the problem by doing the following steps:

Downloading this Kext from Releases: https://github.com/OpenIntelWireless/itlwm
As well as
Downloading this Program from Releases:
https://github.com/OpenIntelWireless/HeliPort

And then copying the .kext file to efi/clover/kexts/other and running the following command inside this folder in the terminal:

sudo chown -R root:wheel itlwm.kext

After completing this step you need to install the program from the second link and run it from your launchpad/Program folder

I hope I could help you

(MacOS Mojave 10.14.6)
